version: "3"
services:
  backend:
    build: ./be
    ports:
      - "6996:6996"
    restart: always
    environment:
      IPV4_ADDRESS: 10.45.25.52
      TOKEN_KEY: secret
      TZ: Asia/Ho_Chi_Minh
      serverKeyNotification: AAAADKwcu4c:APA91bGB_R6tQlpKrCCvGFn0JlFPhZQZSFveHfJFI-NSNhsMl2QLSsc7DQKJwF338Ojvb3I_FfjVeF_yrMNFCgWcLqHohd6ZPsMEd5Hr0jQENgwt6NH0j2NdivtCXIzx5l2p5Zw44BNo
      PORT: 6996
      MONGODB_URI: "mongodb+srv://vuhuy:7D8SsMgQbeLCDCms@hotel-booking.gujng51.mongodb.net/hotel_booking?retryWrites=true&w=majority"
    volumes:
      - ./env:/fe/admin-web-booking/src/api
    command: yarn start

  web-admin:
    build: ./fe/admin-web-booking
    ports:
      - "7102:3000"
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
      PORT: 3000
    volumes:
      - ./env:/web-admin/src/api
    command: yarn start
    depends_on:
      - backend

